apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-analysis
  labels:
    app: churn-analysis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: churn-analysis
  template:
    metadata:
      labels:
        app: churn-analysis
    spec:
      containers:
      - name: churn-analysis
        image: churn-analysis:latest
        ports:
        - containerPort: 8501
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: churn-secrets
              key: database-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: churn-analysis-service
spec:
  selector:
    app: churn-analysis
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8501
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
